---
- name: make sure vim is installed
  apt: 
    name: vim
    state: present
  tags: vim

- name: configure vim
  template:
    src: vimrc.j2
    dest: /etc/vim/vimrc.local
    owner: root
    group: root
    mode: 0644
  tags: vim
